### PR TITLE
Added Lithuanian language to selectable language list

### PR DESCRIPTION
**Pull request by Viliasas**
I have been translating movies in TheMovieDB to Lithuanian language and I would like to be able to select it in Plex interface.

### CODE REVIEW

**Comment by Viliasas** [comment]
@sander1 Would you be able to aprove this pull request?

**Comment by Viliasas** [comment]
@elan Maybe you could aprove this pull request?

**Comment by maxGreenblatt** [comment]
Hey - unfortunately, language approvals are not as simple as they appear. They require work outside of the agents and in the server to work. And the way in which languages have been implemented on the server means it would also require work by the web team, as well. Apologies! There is a long term plan for improving language support, but we aren't there yet

**Comment by Viliasas** [comment]
@maxGreenblatt My understanding was that this change would add Lithuanian language to TheMovieDB agents movie matching language list. Which in turn enable movie matching in this language.

I only want that TheMovieDB agent would return translated title, description and maybe get language specific poster. Would it really require additional work on Plex team to store this data and display it in the web? It would seem that most of the issues should have been resolved when other languages were added to the selectable languages list.

**Comment by maxGreenblatt** [comment]
This has to do with how we store the languages in the database - they are ordered, so adding a new language ends up being more complicated than we want it to be. I will discuss with the team on Monday and try to figure out if there is a workaround to resolve this. This is one of those things that seems like it should be trivial but in the past it hasn't been.

**Comment by Viliasas** [comment]
Thank you. It would mean me a lot if I could contribute to TheMovieDB and see those changes reflected in Plex.

**Comment by sander1** [comment]
> This has to do with how we store the languages in the database - they are ordered, so adding a new language ends up being more complicated than we want it to be.

A little bit explained more here: https://github.com/plexinc-agents/TheMovieDB.bundle/commit/f22a8b56203058979b1bc15d5c5893f9bc71d8f3#diff-a7f5bee015abcba24763f9e62e01df74R50

**Comment by Viliasas** [comment]
@sander1 Would it be ok if I would add it at the end of the list? At this point it doesn't seem to be listed alphabetically.

**Comment by Viliasas** [comment]
Would it be ok if I would add it at the end of the list?

**Comment by sander1** [comment]
> Would it be ok if I would add it at the end of the list?

That would, in theory, be a solution and circumvent the current issues with list preferences. The other issue is that this fork is no longer the active fork. Code in here is pretty old. Current version of the agent is maintained somewhere else (somewhere I have no access to).

**Comment by Viliasas** [comment]
@sander1 Thanks for your help. It seemed odd that last changes to this repository were made in 2015.

@maxGreenblatt Could you add Lithuanian language, to TheMovieDB agents allowed language list, as the last item? Or is it unacceptable due to the list being alphabetically ordered?

**Comment by maxGreenblatt** [comment]
Sorry for the delay - I've had to deal with a couple other things the first part of this week. I will bring up adding a language to the end of the list - in the past I've been told no, but it's been a while since I've asked, so maybe folks have softened their position :)

**Comment by Viliasas** [comment]
Maybe language array could have a second array which could be used for sorting them in places where their position matters. I mean like, which language should be at which position. This would allow adding languages to the end of the list, but displaying them in a different order.

**Comment by elan** [comment]
(I'm not clear on why there is an ordering component to adding languages, personally.)

**Comment by maxGreenblatt** [comment]
Ah, @elan - you're correct, I was confusing how the Plex Movie agent uses countries and languages - we can accept any language that PMS understands, but we can't add additional countries for localized content ratings and release dates. I'll get this committed to the private versions of the agents.

**Comment by Viliasas** [comment]
Thank you all, for your help!

If I understand correctly, I can expect Lithuanian language to be available in the next Plex update?

**Comment by maxGreenblatt** [comment]
I can't promise the next update, because I don't know how PMS is doing release cycles these days, but it will be in a future update.

Do you happen to have a movie on TMDB that have Lithuanian language metadata?

**Comment by Viliasas** [comment]
[Cars 3](https://www.themoviedb.org/movie/260514-cars-3) has Lithuanian title, description and a poster.

**Comment by maxGreenblatt** [comment]
Awesome - thanks!

**Comment by Viliasas** [comment]
Hey, @maxGreenblatt ! Just wanted to check on the status of this change. Has it been implemented? :)

**Comment by Viliasas** [comment]
@maxGreenblatt Any updates?

**Pull request closed without merging**
